#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
os = "#7AA2f7"
closer = "p:os"
terminal-red = "#f7768e"
pistachio-green = "#9ece6a"
terminal-green = "#73daca"
terminal-yellow = "#e0af68"
terminal-blue = "#7aa2f7"
celeste-blue = "#b4f9f8"
light-sky-blue = "#7dcfff"
terminal-white = "#c0caf5"
white-blue = "#a9b1d6"
blue-bell = "#9aa5ce"
pastal-grey = "#cfc9c2"
terminal-magenta = "#bb9af7"
blue-black = "#565f89"
terminal-black = "#414868"

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "p:os"
style = "plain"
template = "{{.Icon}} "
type = "os"

[[blocks.segments]]
foreground = "p:terminal-magenta"
style = "plain"
template = "{{ .UserName }}@{{ .HostName }} "
type = "session"

[[blocks.segments]]
foreground = "p:celeste-blue"
style = "powerline"
template = "î—¾ {{ .Path }} "
type = "path"

[blocks.segments.properties]
folder_icon = "î—¾"
home_icon = "~"
style = "full"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "p:light-sky-blue"
foreground_templates = [
	"{{ if or (.Working.Changed) (.Staging.Changed) }}p:terminal-red{{ end }}",
	"{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:light-sky-blue {{ end }}",
	"{{ if gt .Ahead 0 }}p:terminal-blue{{ end }}",
	"{{ if gt .Behind 0 }}p:celeste-blue{{ end }}",
]
template = "{{ .UpstreamIcon }} {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}â‡£{{ end }}{{ if gt .Ahead 0 }}â‡¡{{ end }}"

[blocks.segments.properties]
branch_icon = "îœ¥ "
cherry_pick_icon = "îŠ› "
commit_icon = "ï— "
fetch_status = true
fetch_upstream_icon = true
merge_icon = "îœ§ "
no_commits_icon = "ïƒƒ "
rebase_icon = "îœ¨ "
revert_icon = "ïƒ¢ "
tag_icon = "ï’ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "argocd"
style = "powerline"
powerline_symbol = "î‚°"
template = "{{ .Name }}:{{ .User }}@{{ .Server }} "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "aws"
style = "powerline"
powerline_symbol = "î‚°"
template = "î­ {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "az"
style = "powerline"
powerline_symbol = "î‚°"
template = "î¯˜ {{ .EnvironmentName }}"

[blocks.segments.properties]
source = "pwsh"

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "azd"
style = "powerline"
powerline_symbol = "î‚°"
template = "î¯˜ {{ .DefaultEnvironment }} "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "azfunc"
style = "powerline"
powerline_symbol = "î‚°"
template = "ïƒ§ {{ .Full }} "

[blocks.segments.properties]
fetch_version = true
display_mode = "files"

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "bun"
style = "plain"
template = "ğŸ¥Ÿ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "deno"
style = "plain"
template = "î˜¨ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "dotnet"
style = "plain"
template = "î¿ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "elixir"
style = "plain"
template = "î˜­ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "flutter"
style = "plain"
template = "îŠ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "gcp"
style = "plain"
template = "î² {{.Project}} :: {{.Account}} "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "firebase"
style = "plain"
template = "ó°¥§ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "go"
style = "plain"
template = "î˜§ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "haskell"
style = "plain"
template = "î˜Ÿ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "java"
style = "plain"
template = "îœ¸ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "kotlin"
style = "plain"
template = "<b>K</b> "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "kubectl"
style = "plain"
template = "ï´± {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "lua"
style = "plain"
template = "î˜  "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "node"
style = "plain"
template = "îœ˜ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "ocaml"
style = "plain"
template = "î™º {{ .Full }} "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "php"
style = "plain"
template = "îœ½ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "python"
style = "plain"
template = "îˆµ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "quasar"
style = "plain"
template = "î©ª {{.Full}}{{ if .HasVite }} î¬© {{ .Vite.Version }}{{ end }} "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "rust"
style = "plain"
template = "î¨ "

[[blocks.segments]]
foreground = "p:terminal-blue"
type = "pulumi"
style = "diamond"
powerline_symbol = "îƒ"
template = "{{ .Stack }}{{if .User }} :: {{ .User }}@{{ end }}{{ if .URL }}{{ .URL }}{{ end }}"

[[blocks.segments]]
style = "plain"
foreground = "p:closer"
template = "ï„…"
type = "text"

[[blocks]]
alignment = "right"
type = "rprompt"

[[blocks.segments]]
foreground = "p:celeste-blue"
style = "plain"
template = "î®¢  {{ .FormattedMs }} "
type = "executiontime"

[blocks.segments.properties]
style = "roundrock"
